version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime
    networks:
      - internal

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - internal

  db:
    image: postgres:14.5
    container_name: db
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - internal

  composer:
    restart: 'no'
    image: composer:2.3
    command: install
    volumes:
      - .:/app
    networks:
      - internal

networks:
  internal:
    driver: bridge